apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config #2
data:
  myvalue: "clarus-chart configmap example"
  course: {{ .Values.course }} #1
  topic: {{ .Values.lesson.topic }} #3
  time: {{ now | date "2006.01.02" | quote }} #3