apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      # ilk örnek
      # containers:
      #   - name: demo
      #     image: clarusway/demo:hello
      #     ports:
      #     - containerPort: 8888
      containers:
        - name:  demo
          image: clarusway/demo:hello-config-file # clarusway/demo:hello-config-env
          ports:
            - containerPort: 8888
          # # env:
          # #   - name: GREETING
          # #     # value: selam
          # #     # 2. örnek altaekledik
          # #     valueFrom:
          # #       configMapKeyRef:
          # #         name: demo-config
          # #         key: greeting
          # envFrom:
          # - configMapRef:
          #     name: demo-config
          volumeMounts:
          - mountPath: /config/
            name: demo-config-volume
            readOnly: true
      volumes:
      - name: demo-config-volume
        configMap:
          name: demo-config
          items:
          - key: config
            path: demo.yaml
