apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/pv-data"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: mongo
    app: todoapp
spec:
  selector:
    app: mongo
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    name: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
        app: todoapp
    spec:
      containers:
      - name: mongo
        image: mongo:5.0
        ports:
          - containerPort: 27017
        volumeMounts:
          - name:  mongo-storage
            mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: db-pv-vol-claim
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  app: todoapp
  labels:
    name:  web
    app: todoapp
spec:
  selector:
    app: web
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
    protocol: TCP
    name: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-vol-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        name: web
        app: todoapp
    spec:
      containers:
      - name: myweb
        image: clarusway/todo
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
          requests:
            memory: "250Mi"
            cpu: "80m"
        env:
          - name: "DBHOST"
            value: db-service
