apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        name: web
        app: todoapp
    spec:
      containers:
      - name: latifweb
        image: clarusway/todo
        imagePullPolicy: Always
        ports:
          - containerPort: 3005 
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
          requests:
            memory: "250Mi"
            cpu: "80m"
        env:
          - name: "DBHOST"
            value: db-service
        
