apiVersion: v1
kind: Service
metadata:
  name: web-service
  app: todoapp
  labels:
    name:  web
    app: todoapp
spec:
  selector:
    app: web
  type: NodePort
  ports:
  - port: 3005
    targetPort: 3005
    nodePort: 30001
    protocol: TCP
    name: http
