kind: Service
apiVersion: v1
metadata:
  name: web-flask-svc
  labels:
    app: web-flask
  namespace: demo
spec:
  type: NodePort
  selector:
    app:  web-flask 
  ports:
  - name:  deneme
    port:  3000
    targetPort:  5000
    nodePort: 32001
