apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcp
  labels:
    name: liveness-tcp
spec:
  containers:
  - name: liveness-tcp
    image: mysql:latest
    resources:
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "123456"
    ports:
      - containerPort: 3306
    livenessProbe:
      tcpSocket:
        port: 3306
      initialDelaySeconds: 15
      periodSeconds: 20
