apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-3g
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual 
  hostPath:
    path: "/home/ubuntu/pv-data"
