apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-6g
spec:
  capacity:
    storage: 7Gi # 6Gi ->  7Gi olarak degistirildi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual 
  hostPath:
    path: "/home/ubuntu/pv-data"
