apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    environment: dev
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: # Bu komutla "value" varsa o Node'da olusturur, yoksa herhangi olusturmaz.
            nodeSelectorTerms:
              - matchExpressions:
                  - key: size
                    operator: In # In icinde, NotIn icinde degil.
                    values:
                      - large 
                      - medium