apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        # value: admin
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        # value: 1f2d1e2e67df
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  restartPolicy: Never