apiVersion: v1
kind: Pod
metadata:
  name: latif-pod
  labels:
    name: latif-web
spec:
  containers:
  - name: latif-pv-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: latif-pv-storage
  volumes:
    - name: latif-pv-storage
      persistentVolumeClaim:
        claimName: latif-pv-claim
